"""initial schema

Revision ID: a7ecf446f4a0
Revises: 
Create Date: 2026-05-06 11:57:01.806325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ecf446f4a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalysts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=True),
    sa.Column('known_activity', sa.Float(), nullable=False),
    sa.Column('known_selectivity', sa.Float(), nullable=False),
    sa.Column('known_stability', sa.Float(), nullable=False),
    sa.Column('activity_unit', sa.String(length=50), nullable=False),
    sa.Column('selectivity_unit', sa.String(length=50), nullable=False),
    sa.Column('stability_unit', sa.String(length=50), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('pressure_min', sa.Float(), nullable=True),
    sa.Column('pressure_max', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('input_species', sa.JSON(), nullable=True),
    sa.Column('output_species', sa.JSON(), nullable=True),
    sa.Column('default_temp_c', sa.Float(), nullable=False),
    sa.Column('default_pressure_bar', sa.Float(), nullable=False),
    sa.Column('default_cost_weight', sa.Float(), nullable=False),
    sa.Column('default_sustainability', sa.Float(), nullable=False),
    sa.Column('pathway_template', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('catalyst_reaction_compat',
    sa.Column('catalyst_id', sa.String(length=36), nullable=False),
    sa.Column('reaction_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalysts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('catalyst_id', 'reaction_id')
    )
    op.create_table('kg_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('catalyst_id', sa.String(length=36), nullable=True),
    sa.Column('reaction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalysts.id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('reaction_id', sa.String(length=36), nullable=True),
    sa.Column('reaction_text', sa.Text(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('pressure_bar', sa.Float(), nullable=False),
    sa.Column('cost_weight', sa.Float(), nullable=False),
    sa.Column('sustainability', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pathway_steps', sa.JSON(), nullable=True),
    sa.Column('pareto_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kg_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kg_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['kg_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discovery_run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=True),
    sa.Column('predicted_activity', sa.Float(), nullable=False),
    sa.Column('predicted_selectivity', sa.Float(), nullable=False),
    sa.Column('predicted_stability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.String(length=10), nullable=False),
    sa.Column('badge', sa.String(length=20), nullable=False),
    sa.Column('active_learning_hint', sa.Text(), nullable=True),
    sa.Column('generative_model', sa.String(length=100), nullable=False),
    sa.Column('computed_properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('actual_temp_c', sa.Float(), nullable=True),
    sa.Column('actual_pressure_bar', sa.Float(), nullable=True),
    sa.Column('catalyst_loading_mg_l', sa.Float(), nullable=True),
    sa.Column('reaction_time_h', sa.Float(), nullable=True),
    sa.Column('actual_activity', sa.Float(), nullable=False),
    sa.Column('actual_selectivity', sa.Float(), nullable=False),
    sa.Column('actual_stability', sa.Float(), nullable=False),
    sa.Column('model_confidence_before', sa.Float(), nullable=True),
    sa.Column('model_confidence_after', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiments')
    op.drop_table('candidates')
    op.drop_table('kg_edges')
    op.drop_table('discovery_runs')
    op.drop_table('projects')
    op.drop_table('kg_nodes')
    op.drop_table('catalyst_reaction_compat')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reactions')
    op.drop_table('catalysts')
    # ### end Alembic commands ###
